version: '2'
 
services:
  package_drone:
    image: stackhead/package_drone
    build:
      context: .
      dockerfile: virtualization/package_drone.Dockerfile
    container_name: package_drone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - package-drone-data:/var/lib/package-drone-server/storage
    ports:
      - "8083:8080"
    restart: always
volumes:
  package-drone-data: {}

